
server:
  port: 8080
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    password: user
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      file-size-threshold: 2KB
application:
  security:
    jwt:
      secret-key: el6KhpnXekcNJ4nstYb0QwUaSkTKeWE5
      expiration: 86400000
      refresh-token:
        expiration: 604800000

