
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    password: user
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: Musobek2345Muhammad
      expiration: 86400000
      refresh-token:
        expiration: 604800000

