name: Build & Deploy Spring App
on:
  push:
    branches:  
       - main
  pull_request:
    branches:
      - main  
jobs:
  deployment:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17


      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name:  Build the application
        run:
          mvn clean
          mvn -B package --file pom.xml

      - name: Unit Tests
        run: mvn -B test --file pom.xml
      - name:  Build the application
        run:
          mvn clean
          mvn -B package --file pom.xml

